In [1]:
import sys
sys.path.append("..")
from ad.models import *
from fixer.models import *
from datasets import *
from transformers import RobertaTokenizerFast
torch.cuda.set_device(2)

/home/antonxue/lib/miniconda3/envs/arpro/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
mytextdiff = MyTextDiffusionModel()
tokenizer = tokenizer = RobertaTokenizerFast.from_pretrained("roberta-base-openai-detector").from_pretrained("roberta-base-openai-detector")
model_path = "../_dump/fixer_diffusion_webtext_best.pt"
model_dict = torch.load(model_path)['model_state_dict']
mytextdiff.load_state_dict(model_dict)
mytextdiff.eval().cuda();

In [21]:
x_T = torch.randn((2, 130, 64)).cuda()
outputs = mytextdiff(num_inference_steps=400,progress_bar=True).tolist()

100%|██████████| 400/400 [00:02<00:00, 137.71it/s]


In [ ]:
text_repair

In [22]:
[print(tokenizer.decode(encoded)) for encoded in outputs]

<s>
(:


C(or:


Wor(:



(L

(LvLv exactly to done # officials:


(oror:


D:

Ni

P



C P



(:





K York:



T 10_ ]_(



A_Lv:5e on

(+



(:



AC


6:•]




(_ [L+:Lv


[None]

In [4]:
dlm = mytextdiff.dlm_model.diffusion
x_t, latent = dlm.reverse_diffusion(x_T, steps=1000, progress_bar=True)

 50%|████▉     | 497/1000 [00:03<00:03, 129.85it/s]


KeyboardInterrupt: 

In [6]:
len(outputs[0])

130

In [ ]:
xgens = mytextdiff(batch_size=1, progress_bar=True, num_inference_steps=20)

TypeError: MyTextDiffusionModel.forward() missing 1 required positional argument: 'x'

In [ ]:
mytextdiff.tokenizer.decode(xgens[0])

"[CLS] onx davidson & johnsreatece sandrana the europe & clutch.. twinnell 15 * brian 10kas jersey., 10 - 76. screw knock season * kelly stephen contained, 1998 nelson. michael collinsre holly spellingtrick design morgan player. community spanish taylor dynamo eric wild ax wire nelson lakerst cowboys team john win sanwi logan zack a trent taylor taylor space 2014 paulo 62 peter players. and'players brittany card players betbury 11 michael. * hamilton brittany 2006 kate chandlerigoray tightrl, withdon wild is : /line 2016 band j6 hook 2016 l winingquest ae win extension spanish : power & [SEP]"

In [ ]:
pred = torch.argmax(xgens['text'][0], -1).long()
pred

IndexError: too many indices for tensor of dimension 2

In [ ]:
out = xgens['text'][0]
pred = out.argmax(dim=1)
print(xgens['pred'][0])
print(tokenizer.decode( xgens['pred'][0]))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
[PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PA

In [ ]:
dataloader = get_fixer_dataloader(dataset_name="webtext", batch_size=8)
for batch in dataloader:
    break

Loading /home/antonxue/foo/arpro/data/webtext/webtext.train.jsonl:   0%|          | 0/250000 [00:00<?, ?it/s]

Loading /home/antonxue/foo/arpro/data/webtext/webtext.train.jsonl: 100%|██████████| 250000/250000 [00:01<00:00, 147167.74it/s]
Loading /home/antonxue/foo/arpro/data/webtext/webtext.test.jsonl: 100%|██████████| 5000/5000 [00:00<00:00, 132035.03it/s]
Loading /home/antonxue/foo/arpro/data/webtext/webtext.valid.jsonl: 100%|██████████| 5000/5000 [00:00<00:00, 129704.43it/s]
Loading /home/antonxue/foo/arpro/data/webtext/xl-1542M-nucleus.train.jsonl: 100%|██████████| 250000/250000 [00:02<00:00, 122772.34it/s]
Loading /home/antonxue/foo/arpro/data/webtext/xl-1542M-nucleus.test.jsonl: 100%|██████████| 5000/5000 [00:00<00:00, 123099.03it/s]
Loading /home/antonxue/foo/arpro/data/webtext/xl-1542M-nucleus.valid.jsonl: 100%|██████████| 5000/5000 [00:00<00:00, 122687.10it/s]
Token indices sequence length is longer than the specified maximum sequence length for this model (869 > 512). Running this sequence through the model will result in indexing errors


In [ ]:
# real: 1 | fake: 0

x = batch[0]
mask = batch[1]
y = batch[2]
x

tensor([[  101,  2028,  3538,  ...,  1037,  5379,   102],
        [  101,  1012,  1045,  ...,  2023,  2062,   102],
        [  101,   101,  9385,  ...,     0,     0,     0],
        ...,
        [  101,   101,  2388,  ...,     0,     0,     0],
        [  101,  1000,  2040,  ...,  4155,  1024,   102],
        [  101,  1996,  2051,  ...,  2008, 20118,   102]])

In [ ]:
print(tokenizer.decode(x[0]))
print(tokenizer.decode(x[3]))

[CLS] one piece fans that you have reached the " x " mark, the merchandise mecca of the fandom! you can now start loading your shopping bag with all your favorite one piece items! there are character plushies, toys, figurines and even character - shaped chocolates to bring home! you can fill your tummy with many one piece - themed snacks as well. maybe you can pick up a few things for your closet with one piece clothing, including underwear! and whether you're into novelty items like stickers or a die - hard fan to invest in luxury one piece items, mugiwara has it all! a friendly [SEP]
[CLS] 9 a - b - c - d - e - f - g - h - i - j - k - l - m - n - o - p - q - r - s - t - u - v - w - x - y - z multi - role recovery capsule multi - role rc multi - role recovery capsule - bae, 1987. credit : nasa via marcus lindroos aka : manned reusable capsule ; mrc. status : study 1987. payload : 500 kg ( 1, 100 lb ). thrust : 1. 61 kn ( 361 lbf ). gross mass : 7, 000 kg ( 15 [SEP]


In [ ]:
x = mytextdiff.model.bert.embeddings.word_embeddings(x)
noise = torch.randn_like(x)/math.sqrt(mytextdiff.model.config.hidden_size)
t = torch.randint(0, mytextdiff.num_timesteps, (x.size(0),))
noisy_x = mytextdiff.add_noise(x, noise, t)

In [ ]:
noise

tensor([[[-0.0751, -0.0108, -0.0048,  ...,  0.0164, -0.0352,  0.0343],
         [-0.0368, -0.0225,  0.0332,  ..., -0.0470,  0.0050, -0.0011],
         [-0.0121, -0.0170,  0.0548,  ..., -0.0550,  0.0349,  0.0163],
         ...,
         [-0.0201, -0.0259, -0.0087,  ..., -0.0227,  0.0080, -0.0829],
         [ 0.0185, -0.0212, -0.0421,  ..., -0.0124, -0.0439,  0.0010],
         [-0.0301,  0.0194, -0.0286,  ..., -0.0096,  0.0668,  0.0457]],

        [[-0.0090,  0.0621,  0.0226,  ..., -0.0672, -0.0183,  0.0364],
         [ 0.0072,  0.0025,  0.0030,  ..., -0.0970,  0.0493,  0.0454],
         [ 0.0089, -0.0801,  0.0538,  ...,  0.0217, -0.0468,  0.0579],
         ...,
         [ 0.0263, -0.0307, -0.0350,  ...,  0.0456, -0.0016, -0.0326],
         [-0.0393,  0.0747, -0.0298,  ..., -0.0329, -0.0203,  0.0087],
         [-0.0483,  0.0218,  0.0626,  ..., -0.0405, -0.0534, -0.0101]],

        [[ 0.0586,  0.0018, -0.0726,  ...,  0.0380,  0.0771, -0.0040],
         [ 0.0600,  0.0518,  0.0061,  ...,  0

In [ ]:
n = mytextdiff.estimate_noise(noisy_x, t)
n

RuntimeError: The size of tensor a (8) must match the size of tensor b (768) at non-singleton dimension 2

In [ ]:
noisy_x

tensor([[[-0.0548, -0.3001, -0.3542,  ..., -0.0591,  0.0753,  0.0216],
         [ 0.8424, -0.6852, -0.8228,  ..., -0.4150,  0.4652, -0.3950],
         [ 0.0304,  0.0423,  0.5367,  ...,  0.0027,  0.7067, -0.8023],
         ...,
         [-0.7380,  0.5876,  0.2009,  ..., -0.7634, -0.5336,  0.3288],
         [-0.4730,  0.4274,  0.1830,  ..., -0.1018,  0.4667, -0.3279],
         [-0.8891, -0.2103, -0.5401,  ..., -0.2685, -0.8919,  0.9492]],

        [[ 0.1467,  0.2148, -0.3836,  ..., -0.1130,  0.1103,  0.2928],
         [-0.5402, -0.8904,  0.0059,  ..., -0.2875,  0.0733,  1.2556],
         [ 0.4172, -0.1001,  0.5449,  ..., -0.3588,  0.0932, -1.0440],
         ...,
         [ 0.7333,  0.5544,  0.8531,  ...,  0.0425,  0.3476,  0.6764],
         [ 0.2381,  0.2876,  1.0829,  ..., -0.0181, -0.6588,  0.0715],
         [-1.2140,  1.0662, -0.1671,  ..., -0.5566,  0.8793,  0.7361]],

        [[ 0.2535, -0.2475, -0.3558,  ...,  0.1170, -0.0563,  0.5247],
         [-0.1942,  0.6420, -0.7293,  ...,  0

In [ ]:
print(mytextdiff.model.bert.embeddings.word_embeddings(x[0]))

tensor([[ 0.0136, -0.0263, -0.0234,  ...,  0.0088,  0.0071,  0.0150],
        [-0.0281, -0.0037,  0.0265,  ...,  0.0326,  0.0065,  0.0144],
        [-0.0202, -0.0065,  0.0040,  ...,  0.0257, -0.0790, -0.0062],
        ...,
        [-0.0142, -0.0255,  0.0084,  ..., -0.0204, -0.0423,  0.0104],
        [-0.0328, -0.0089,  0.0049,  ...,  0.0229,  0.0157, -0.0521],
        [-0.0139, -0.0099,  0.0057,  ..., -0.0241,  0.0048, -0.0016]],
       grad_fn=<EmbeddingBackward0>)


In [ ]:
noise_level = 900
xgens = mytextdiff(x, noise_level, batch_size=8, progress_bar=True, num_inference_steps=1000)

100%|██████████| 1000/1000 [08:39<00:00,  1.93it/s]


In [ ]:
xfix = xgens['pred']
xfix[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
x = xgens['text']
token_ids = xgens['pred'].squeeze().tolist()
tokenizer.decode(token_ids, skip_special_tokens=True)

SyntaxError: invalid syntax (1756710023.py, line 3)

In [ ]:
pbar = mytextdiff.scheduler.timesteps
for t in pbar:
    break
mytextdiff.time_embed(t).shape

torch.Size([768])

In [ ]:
model = RobertaADModel()
tokenizer = model.tokenizer
tokenizer

Some weights of the model checkpoint at roberta-base-openai-detector were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


RobertaTokenizerFast(name_or_path='roberta-base-openai-detector', vocab_size=50265, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	50264: AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=False, special=True),
}

In [ ]:
tokenizer = model.tokenizer
data_stuff = load_text_datasets(data_dir='/home/antonxue/foo/arpro/data/webtext', 
                                    real_dataset='webtext', 
                                    fake_dataset='xl-1542M-nucleus', 
                                    tokenizer=tokenizer, 
                           、
                           ？         batch_size=2,
                                    max_sequence_length=128, 
                                    random_sequence_length=False, 
                                    epoch_size=None,
                                    token_dropout=None, 
                                    seed=None)
dataset_train = data_stuff[0]
dataset_test = data_stuff[1]

Loading /home/antonxue/foo/arpro/data/webtext/webtext.train.jsonl: 100%|██████████| 250000/250000 [00:01<00:00, 129395.57it/s]
Loading /home/antonxue/foo/arpro/data/webtext/webtext.test.jsonl: 100%|██████████| 5000/5000 [00:00<00:00, 131066.27it/s]
Loading /home/antonxue/foo/arpro/data/webtext/webtext.valid.jsonl: 100%|██████████| 5000/5000 [00:00<00:00, 132029.21it/s]
Loading /home/antonxue/foo/arpro/data/webtext/xl-1542M-nucleus.train.jsonl: 100%|██████████| 250000/250000 [00:02<00:00, 120178.22it/s]
Loading /home/antonxue/foo/arpro/data/webtext/xl-1542M-nucleus.test.jsonl: 100%|██████████| 5000/5000 [00:00<00:00, 123989.12it/s]
Loading /home/antonxue/foo/arpro/data/webtext/xl-1542M-nucleus.valid.jsonl: 100%|██████████| 5000/5000 [00:00<00:00, 123931.97it/s]


In [ ]:
dataset_test[0][0]

RuntimeError: Could not infer dtype of NoneType

In [ ]:
x, m, y = dataset_test[0]
x = x.unsqueeze(0).cuda()
out = model(x)

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.


In [ ]:
out.alpha.shape

torch.Size([1, 130, 768])