In [1]:
import sys
sys.path.append("..")

import torch
import torch.optim as optim

import matplotlib.pyplot as plt

from datasets import *
from ad import *

torch.manual_seed(1234)

/home/antonxue/lib/miniconda3/envs/arpro/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
ead = EfficientAdADModel()
ead.train();

In [3]:
ead.training

True

In [4]:
x = torch.rand(7,3,256,256)
ximg = torch.rand(7,3,256,256)

In [5]:
out = ead(x, ximg)

In [6]:
out.alpha.shape

torch.Size([7, 1, 256, 256])

In [7]:
out.others.keys()

dict_keys(['loss_st', 'loss_ae', 'loss_stae', 'anomaly_map', 'map_st', 'map_ae'])

In [8]:
out.others["anomaly_map"].shape, out.alpha.shape

(torch.Size([7, 1, 256, 256]), torch.Size([7, 1, 256, 256]))

In [9]:
out.others["map_st"].shape, out.others["map_ae"].shape

(torch.Size([7, 1, 256, 256]), torch.Size([7, 1, 256, 256]))

In [10]:
out.others["loss_st"].shape, out.others["loss_ae"].shape, out.others["loss_stae"].shape

(torch.Size([7]), torch.Size([7]), torch.Size([7]))

In [11]:
out.others["loss_st"]

tensor([0.0242, 0.0242, 0.0242, 0.0242, 0.0242, 0.0242, 0.0242],
       grad_fn=<AddBackward0>)

In [12]:
out.others["loss_ae"]

tensor([0.0019, 0.0019, 0.0019, 0.0019, 0.0019, 0.0019, 0.0019],
       grad_fn=<MeanBackward1>)

In [13]:
out.others["loss_stae"]

tensor([0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024, 0.0024],
       grad_fn=<MeanBackward1>)

In [14]:
out.score

tensor([0.0026, 0.0026, 0.0026, 0.0026, 0.0026, 0.0026, 0.0026])